In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 24.7 MB/s  0:00:00m0:00:010:01
Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 47.3 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.0 pandas-3.0.3

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip

In [3]:
# Importamos libreria
import pandas as pd

# Tipos de datos
#   lista: []
#   diccionario: {}
#   tupla: ()

In [ ]:
data = [['Juan', 25], ['Pedro', 34], ['Luis', 45]]

df = pd.DataFrame(data, columns = ['Nombre', 'Edad'])

In [7]:
df

  Nombre  Edad
0   Juan    25
1  Pedro    34
2   Luis    45

In [8]:
# Crear un data frame a partir de un diccionario

data = {
    'Nombre': ['Juan', 'pedro', 'Luis'],
    'Edad': [25, 26, 30]
}

df = pd.DataFrame(data)

In [10]:
df

  Nombre  Edad
0   Juan    25
1  pedro    26
2   Luis    30

In [12]:
# Leer un archivo de una ruta indicada
df = pd.read_csv('utils/data/data.csv')

df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [15]:
# Leer un archivo sin extension y con un separador especial
df = pd.read_csv('utils/data/data', sep = '|')

df

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla